title: My Blog
description: A blog about economics, business strategy, technology and data.
url: https://youssefnim.github.io
author: Youssef Nim
theme: custom theme # Example theme
plugins:
  - jekyll-feed # Add this for RSS feed generation
